### ISSUE TITLE
add Slack Team

### ISSUE THREAD

**Issue by Dr-G** [numfocus/summit#4]
We have created a Slack Team specifically for the Summit so folks can easily connect, receive announcements, and search for information. You are invited to join it [here](https://join.slack.com/t/nfsummit2018/shared_invite/enQtNDI0MzI1NjI0MTYwLWJmNjNiMTc2ZGIxZjliYTBiYzE1MDQzNTgxYTZhODU4YWVmZDQ2OGJlMDlhYWMwMTVhYzRlMmU1NzIwZTliYjk).

**Comment by aterrel** [comment]
What page do you want this on?
