### ISSUE TITLE
add welcome reception information

### ISSUE THREAD

**Issue by Dr-G** [numfocus/summit#5]
Welcome Reception - Friday, Sep 21 - 6:00-8:00pm

The welcome reception will feature heavy hors d'oeuvres and an opportunity to mingle with your fellow project leaders and NumFOCUS directors, advisers, and staff. 

The location is T45 Restaurant at the Hyatt Centric Times Square, 135 West 45th Street (10036).

**Comment by aterrel** [comment]
done!
